#!/usr/bin/env node
/**
 * Builds `site/qr.js`: the vendored QR encoder as one self-contained browser file.
 *
 * # Why a vendored encoder instead of a dependency
 *
 * The provisioning page has to draw a QR code **offline**, from whatever address
 * the deployment owner types, without a CDN and without a build step they have to
 * trust. That rules out a runtime import and rules out a hosted library: a page
 * whose only job is to hand a phone an address must not itself need the network.
 *
 * So the encoder is vendored (`scripts/vendor/qr/`, MIT, Kazuhiko Arase's
 * `qrcode.js` via the copy npm ships inside `qrcode-terminal`) and flattened into
 * one file here. The upstream modules are `var X = require('./Y')` CommonJS; in one
 * script scope they need no loader at all, so the transform is: drop the `require`
 * lines, drop the `module.exports` lines, concatenate in dependency order, wrap.
 *
 * # Why `--check` exists
 *
 * A generated file that nobody regenerates rots, and a *transformed* generated file
 * can be wrong in a way that still looks fine — the page would simply draw a QR
 * code that no scanner reads. Two checks run here:
 *
 *   1. `--check` rebuilds in memory and compares bytes with `site/qr.js`;
 *   2. both paths (the bundle and the vendored modules) are loaded and their
 *      module matrices are compared for a corpus of real configuration links.
 *
 * The second check is the one that would catch a bad concatenation order, which is
 * the only way this transform can fail silently.
 *
 * Usage:
 *   node scripts/vendor-qr.mjs           # write site/qr.js
 *   node scripts/vendor-qr.mjs --check   # fail if site/qr.js is stale or differs
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import vm from 'node:vm';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = join(HERE, '..');
const VENDOR = join(HERE, 'vendor', 'qr');
const OUT = join(REPO_ROOT, 'site', 'qr.js');

/** Dependency order. Verified functionally below, not by reading the requires. */
const MODULES = [
  'QRMode',
  'QRMath',
  'QRPolynomial',
  'QRErrorCorrectLevel',
  'QRRSBlock',
  'QRMaskPattern',
  'QRBitBuffer',
  'QR8bitByte',
  'QRUtil',
  'index',
];

const HEADER = `/*
 * QR encoder, vendored and flattened. Generated by scripts/vendor-qr.mjs — do not edit.
 *
 *   QRCode for JavaScript
 *   Copyright (c) 2009 Kazuhiko Arase
 *   Licensed under the MIT license: http://www.opensource.org/licenses/mit-license.php
 *   "QR Code" is a registered trademark of DENSO WAVE INCORPORATED.
 *
 * Source: qrcode-terminal 0.12.0 (npm), vendor/QRCode/, which is the node port of
 * Kazuhiko Arase's qrcode.js. Full text: scripts/vendor/qr/LICENSE.
 *
 * Why it is copied into the repository rather than imported: the provisioning page
 * has to draw a QR code offline, for whatever address a deployment owner types,
 * with no CDN and no install step. See scripts/vendor-qr.mjs for the transform and
 * the equivalence check that keeps this file honest.
 *
 * Exposes: window.DSHQR = { QRCode, QRErrorCorrectLevel, renderSvg }
 */

`;

/** My own helper, not vendored: version selection and SVG generation. */
const RENDERER = `
  // -- renderSvg: the only code here that is not the vendored encoder --------
  //
  // The vendored encoder needs a version number chosen by the caller. Byte-mode
  // capacity per version at error-correction level M, which is the level to use for
  // something a phone camera reads off a screen:
  var CAPACITY_M = [0, 14, 26, 42, 62, 84, 106, 122, 152, 180, 213];

  function renderSvg(text, options) {
    var opts = options || {};
    var scale = opts.scale || 6;
    var margin = opts.margin == null ? 4 : opts.margin;
    var level = opts.level == null ? QRErrorCorrectLevel.M : opts.level;

    var version = 0;
    for (var v = 1; v < CAPACITY_M.length; v++) {
      if (text.length <= CAPACITY_M[v]) { version = v; break; }
    }
    if (!version) return null;

    var qr = new QRCode(version, level);
    qr.addData(text);
    qr.make();

    var count = qr.getModuleCount();
    var size = (count + margin * 2) * scale;
    var parts = [
      '<svg xmlns="http://www.w3.org/2000/svg" width="' + size + '" height="' + size +
        '" viewBox="0 0 ' + size + ' ' + size + '" role="img" aria-label="Configuration QR code" shape-rendering="crispEdges">',
      '<rect width="' + size + '" height="' + size + '" fill="#ffffff"/>',
      '<path fill="#000000" d="',
    ];
    for (var row = 0; row < count; row++) {
      for (var col = 0; col < count; col++) {
        if (qr.isDark(row, col)) {
          var x = (col + margin) * scale;
          var y = (row + margin) * scale;
          parts.push('M' + x + ' ' + y + 'h' + scale + 'v' + scale + 'h-' + scale + 'z');
        }
      }
    }
    parts.push('"/></svg>');
    return parts.join('');
  }
`;

function build() {
  const body = MODULES.map((name) => {
    const file = join(VENDOR, `${name}.js`);
    if (!existsSync(file)) throw new Error(`missing vendored module: ${file}`);
    const variable = name === 'index' ? 'QRCode' : name;
    return readFileSync(file, 'utf8')
      .split(/\r?\n/)
      .filter((line) => !/^\s*var\s+\w+\s*=\s*require\(/.test(line))
      // Two shapes of export, and they need different treatment. An inline object
      // literal has to *become* the declaration (`module.exports = {` →
      // `var QRMode = {`), because dropping the line leaves a bare literal that
      // does not parse. An identifier export is already declared above it, so its
      // line is dropped.
      .map((line) =>
        /^\s*module\.exports\s*=\s*\{/.test(line)
          ? line.replace(/^(\s*)module\.exports\s*=\s*\{/, `$1var ${variable} = {`)
          : line,
      )
      .filter((line) => !/^\s*module\.exports\s*=/.test(line))
      .join('\n')
      .trim();
  }).join('\n\n');

  return (
    HEADER +
    '(function (global) {\n' +
    "'use strict';\n\n" +
    body +
    '\n' +
    RENDERER +
    '\n  global.DSHQR = { QRCode: QRCode, QRErrorCorrectLevel: QRErrorCorrectLevel, renderSvg: renderSvg };\n' +
    "})(typeof window !== 'undefined' ? window : this);\n"
  );
}

/** Loads the vendored modules the ordinary way, for comparison. */
function loadVendored() {
  const require = createRequire(import.meta.url);
  const QRCode = require(join(VENDOR, 'index.js'));
  const QRErrorCorrectLevel = require(join(VENDOR, 'QRErrorCorrectLevel.js'));
  return { QRCode, QRErrorCorrectLevel };
}

/** Loads the built bundle the way a browser would. */
function loadBundle(source) {
  const sandbox = { window: {} };
  vm.createContext(sandbox);
  new vm.Script(source).runInContext(sandbox);
  return sandbox.window.DSHQR;
}

/** The corpus: every shape a configuration link actually takes. */
const CORPUS = [
  'dshbyok://setup?target=100.101.102.103',
  'dshbyok://setup?target=100.101.102.103:3080',
  'dshbyok://setup?target=phone.tailnet-name.ts.net&mode=embedded',
  'dshbyok://setup?target=100.101.102.103:3080&mode=system&update=http%3A%2F%2F192.0.2.10%3A8089',
  'dshbyok://setup?target=https%3A%2F%2Fphone.tailnet-name.ts.net%3A8443%2Fhealth',
  'dshbyok://setup?mode=system',
  'dshbyok://setup?target=' + 'a'.repeat(60) + '.ts.net',
  'dshbyok://setup?target=' + 'a'.repeat(160) + '.ts.net',
  'x',
  '',
];

function moduleMatrix(QRCode, QRErrorCorrectLevel, text) {
  const capacities = [0, 14, 26, 42, 62, 84, 106, 122, 152, 180, 213];
  let version = 0;
  for (let v = 1; v < capacities.length; v++) {
    if (text.length <= capacities[v]) {
      version = v;
      break;
    }
  }
  if (!version) return null;
  const qr = new QRCode(version, QRErrorCorrectLevel.M);
  qr.addData(text);
  qr.make();
  const count = qr.getModuleCount();
  let out = '';
  for (let r = 0; r < count; r++) {
    for (let c = 0; c < count; c++) out += qr.isDark(r, c) ? '1' : '0';
    out += '\n';
  }
  return out;
}

function verifyEquivalence(source) {
  const vendored = loadVendored();
  const bundle = loadBundle(source);
  const failures = [];
  for (const text of CORPUS) {
    const want = moduleMatrix(vendored.QRCode, vendored.QRErrorCorrectLevel, text);
    const got = bundle.renderSvg(text, { scale: 1, margin: 0 });
    if (want === null) {
      if (got !== null) failures.push(`expected no QR for ${JSON.stringify(text.slice(0, 40))}`);
      continue;
    }
    if (got === null) {
      failures.push(`bundle refused to render ${JSON.stringify(text.slice(0, 40))}`);
      continue;
    }
    // Reconstruct the matrix from the emitted SVG path and compare cell by cell.
    const cells = new Set();
    for (const m of got.matchAll(/M(\d+) (\d+)h1v1h-1z/g)) cells.add(`${m[1]},${m[2]}`);
    const lines = want.trimEnd().split('\n');
    for (let r = 0; r < lines.length; r++) {
      for (let c = 0; c < lines[r].length; c++) {
        const dark = lines[r][c] === '1';
        if (dark !== cells.has(`${c},${r}`)) {
          failures.push(`matrix mismatch for ${JSON.stringify(text.slice(0, 40))} at ${r},${c}`);
          r = lines.length;
          break;
        }
      }
    }
  }
  return failures;
}

function main() {
  const check = process.argv.includes('--check');
  const source = build();

  const failures = verifyEquivalence(source);
  if (failures.length > 0) {
    console.error('vendored QR bundle does not match the vendored encoder:');
    for (const f of failures) console.error(`  ${f}`);
    process.exit(1);
  }

  if (check) {
    if (!existsSync(OUT)) {
      console.error(`site/qr.js is missing; run: node scripts/vendor-qr.mjs`);
      process.exit(1);
    }
    const current = readFileSync(OUT, 'utf8');
    if (current !== source) {
      console.error('site/qr.js is stale; run: node scripts/vendor-qr.mjs');
      process.exit(1);
    }
    console.log(`site/qr.js ok — matches the vendored encoder over ${CORPUS.length} inputs`);
    return;
  }

  writeFileSync(OUT, source, 'utf8');
  console.log(`wrote site/qr.js (${source.length} bytes); equivalence verified over ${CORPUS.length} inputs`);
}

main();
