package io.github.zero6689.tailnetbyok.net

import io.github.zero6689.tailnetbyok.BuildConfig
import io.github.zero6689.tailnetbyok.R
import io.github.zero6689.tailnetbyok.core.log.SafeLog
import io.github.zero6689.tailnetbyok.core.text.TextRef

/**
 * Resolves a [ProviderId] to an implementation.
 *
 * # Why one provider is loaded reflectively
 *
 * The embedded tsnet provider cannot be referenced from the main source set:
 * it compiles against classes generated by `gomobile bind`, and those only exist
 * when the app is built with `-PwithTsnet=true`. A direct reference would make
 * the default build fail on a machine that has no Go toolchain — which is most
 * machines, and every contributor's first `git clone`.
 *
 * The two ways out are (a) a separate Gradle module per provider, or (b) a
 * single late-bound hook. The module split does not actually remove the problem,
 * because the module *consumer* still has to name the class; it only moves the
 * failure. So this uses (b): the class name is a string, resolved once at
 * startup, and only when the build says the bridge is present.
 *
 * The cost is that R8 cannot see the reference and would strip the class in a
 * release build. That is handled explicitly in `app/proguard-rules.pro`, which
 * keeps `**.net.tsnet.**`. If you add a provider, add its keep rule too — the
 * failure mode otherwise is a release-only `ClassNotFoundException`, i.e. the
 * worst kind.
 */
object ProviderRegistry {

    private const val TAG = "Providers"

    /** Fully-qualified name of the installer that the `tsnet` source set provides. */
    private const val TSNET_INSTALLER =
        "io.github.zero6689.tailnetbyok.net.tsnet.TsnetProviderInstaller"

    private val factories = LinkedHashMap<ProviderId, () -> ConnectivityProvider>()

    /** Providers that failed to load, with the reason, for the diagnostics screen. */
    private val loadFailures = LinkedHashMap<ProviderId, TextRef>()

    @Volatile
    private var initialised = false

    fun initialise() {
        if (initialised) return
        synchronized(this) {
            if (initialised) return

            register(ProviderId.SYSTEM_NETWORK) { SystemNetworkProvider() }
            registerEmbeddedTsnet()

            initialised = true
        }
    }

    /** Instantiates [id], or null when this build/device cannot provide it. */
    fun create(id: ProviderId): ConnectivityProvider? {
        initialise()
        return factories[id]?.invoke()
    }

    /** Every provider this build can actually offer, in preference order. */
    fun available(): List<ProviderId> {
        initialise()
        return factories.keys.toList()
    }

    /** Why a provider is missing, as a translatable message, or null when it loaded. */
    fun failureReason(id: ProviderId): TextRef? {
        initialise()
        return loadFailures[id]
    }

    private fun register(id: ProviderId, factory: () -> ConnectivityProvider) {
        factories[id] = factory
    }

    private fun registerEmbeddedTsnet() {
        if (!BuildConfig.TSNET_ENABLED) {
            loadFailures[ProviderId.EMBEDDED_TSNET] =
                TextRef.of(R.string.provider_unavailable_not_compiled)
            return
        }
        try {
            val installer = Class.forName(TSNET_INSTALLER)
            val method = installer.getMethod("install", ProviderRegistry::class.java)
            method.invoke(null, this)
        } catch (e: ClassNotFoundException) {
            loadFailures[ProviderId.EMBEDDED_TSNET] =
                TextRef.of(R.string.provider_unavailable_bridge_missing)
            SafeLog.w(TAG, "embedded tsnet installer not found", e)
        } catch (e: ReflectiveOperationException) {
            loadFailures[ProviderId.EMBEDDED_TSNET] = TextRef.of(
                R.string.provider_unavailable_bridge_failed,
                e.cause?.message ?: e.message ?: e::class.java.simpleName,
            )
            SafeLog.w(TAG, "embedded tsnet installer failed", e)
        } catch (e: UnsatisfiedLinkError) {
            // The AAR is present but the .so for this ABI is not — a real
            // failure mode on x86 emulators, where arm64-only builds install
            // but explode on first call.
            loadFailures[ProviderId.EMBEDDED_TSNET] = TextRef.of(R.string.provider_unavailable_no_abi)
            SafeLog.w(TAG, "embedded tsnet native library unavailable", e)
        }
    }

    /** Called by the tsnet source set during [initialise]. Not for UI code. */
    internal fun registerEmbedded(factory: () -> ConnectivityProvider) {
        register(ProviderId.EMBEDDED_TSNET, factory)
        loadFailures.remove(ProviderId.EMBEDDED_TSNET)
    }
}
